//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimaSim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MimaSim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;busactivations&gt;
        ///    &lt;activator id=&quot;cu-&gt;x&quot;&gt;
        ///        &lt;setbus id=&quot;alu_input_x2&quot;/&gt;
        ///        &lt;mainbus value=&quot;42&quot;/&gt;
        ///    &lt;/activator&gt;
        ///    &lt;activator id=&quot;cu-&gt;y&quot;&gt;
        ///        &lt;setbus id=&quot;alu_input_y2&quot;/&gt;
        ///        &lt;mainbus value=&quot;55&quot;/&gt;
        ///    &lt;/activator&gt;
        ///    &lt;activator id=&quot;cu-&gt;accu&quot;&gt;
        ///        &lt;setbus id=&quot;base_to_accu&quot;/&gt;
        ///        &lt;mainbus value=&quot;42&quot;/&gt;
        ///    &lt;/activator&gt;
        ///    &lt;activator id=&quot;cu-&gt;mem&quot;&gt;
        ///        &lt;setbus id=&quot;memory_data2&quot;/&gt;
        ///        &lt;setbus id=&quot;memory_adresss2&quot;/&gt;
        ///        &lt;mainbus value=&quot;100&quot;/&gt;
        ///    &lt;/acti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusMap {
            get {
                return ResourceManager.GetString("BusMap", resourceCulture);
            }
        }
    }
}
